# Home Assistant Configuration
# This is a clean, modular configuration using includes

# Basic configuration
default_config:

# Text to speech
tts:
  - platform: google_translate

# Include REST sensors from separate file
!include gazebo_rest_sensors.yaml

# Group all the gazebo sensors
group:
  gazebo_sensors:
    name: "Gazebo Weather Sensors"
    entities:
      - sensor.gazebo_current_temperature_2
      - sensor.gazebo_current_apparent_temperature_2
      - sensor.gazebo_current_humidity_2
      - sensor.gazebo_hour_0_feels_like_2
      - sensor.gazebo_hour_1_feels_like_2
      - sensor.gazebo_hour_2_feels_like_2
      - sensor.gazebo_hour_3_feels_like_2
      - sensor.gazebo_hour_4_feels_like_2
      - sensor.gazebo_hour_5_feels_like_2
      - sensor.gazebo_hour_6_feels_like_2
      - sensor.gazebo_hour_0_precipitation_2
      - sensor.gazebo_hour_1_precipitation_2
      - sensor.gazebo_hour_2_precipitation_2
      - sensor.gazebo_hour_3_precipitation_2
      - sensor.gazebo_hour_4_precipitation_2
      - sensor.gazebo_hour_5_precipitation_2
      - sensor.gazebo_hour_6_precipitation_2

# ESPHome integration
esphome:
  gazebo_thermostat:
    name: "gazebo-thermostat"
    platform: ESP32
    board: esp32dev
    on_boot:
      priority: -100
      then:
        - logger.log: "Gazebo Thermostat starting up"

# Logging configuration
logger:
  default: info
  logs:
    homeassistant.components.rest: debug
    homeassistant.components.esphome: debug

# Recorder (optional - adjust retention as needed)
recorder:
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.gazebo_hour_1_feels_like_2
      - sensor.gazebo_hour_2_feels_like_2
      - sensor.gazebo_hour_3_feels_like_2
      - sensor.gazebo_hour_4_feels_like_2
      - sensor.gazebo_hour_5_feels_like_2
      - sensor.gazebo_hour_6_feels_like_2
      - sensor.gazebo_hour_1_precipitation_2
      - sensor.gazebo_hour_2_precipitation_2
      - sensor.gazebo_hour_3_precipitation_2
      - sensor.gazebo_hour_4_precipitation_2
      - sensor.gazebo_hour_5_precipitation_2
      - sensor.gazebo_hour_6_precipitation_2

# History (optional - adjust retention as needed)
history:
  purge_keep_days: 7

# Lovelace UI
lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
