# Home Assistant Configuration
# Loads default set of integrations. Do not remove.

default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Include modular configurations
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Include OpenMeteo REST sensors (split into separate files)
rest: !include openmeteo_rest.yaml
group: !include openmeteo_groups.yaml
recorder: !include openmeteo_recorder.yaml

# Text to speech
tts:
  - platform: google_translate

# Bluetooth configuration
bluetooth:

# Device tracker
device_tracker:
  - platform: bluetooth_le_tracker

# Custom sensors
sensor:
  - platform: command_line
    name: "Last Shell Command"
    command: "cat /config/last_shell_command.txt"

# Shell commands
shell_command:
  ping_device: ping -c 1 192.168.0.203 > /dev/null 2>&1 && echo success || echo fail

# Binary sensors
binary_sensor:
  - platform: template
    sensors:
      device_online:
        friendly_name: "Garage Online"
        value_template: "{{ states('shell_command.ping_device') == 'success' }}"
        device_class: connectivity

# Logging configuration
logger:
  default: warning
  logs:
    homeassistant.components.http: debug
    homeassistant.components.rest: debug
    homeassistant.components.esphome: debug

# Lovelace UI
lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module