# Home Assistant Configuration
default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

tts:
  - platform: google_translate

bluetooth:

device_tracker:
  - platform: bluetooth_le_tracker

sensor:
  - platform: command_line
    name: "Last Shell Command"
    command: "cat /config/last_shell_command.txt"

rest:
  - resource: "https://api.open-meteo.com/v1/forecast?latitude=45.2631&longitude=-71.9788&hourly=apparent_temperature,precipitation_probability,temperature,relative_humidity_2m,weathercode&current=temperature_2m,relative_humidity_2m,apparent_temperature&temperature_unit=celsius&precipitation_unit=mm&timezone=auto&forecast_days=1"
    scan_interval: 60
    sensor:
      - name: "Gazebo Current Temperature"
        unique_id: gazebo_current_temperature
        value_template: "{{ value_json['current']['temperature_2m'] }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Gazebo Current Apparent Temperature"
        unique_id: gazebo_current_apparent_temperature
        value_template: "{{ value_json['current']['apparent_temperature'] }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Gazebo Current Humidity"
        unique_id: gazebo_current_humidity
        value_template: "{{ value_json['current']['relative_humidity_2m'] }}"
        unit_of_measurement: "%"
        device_class: humidity
        state_class: measurement

      - name: "Gazebo Hour 0 Feels Like"
        unique_id: gazebo_hour_0_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][now().hour] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 1 Feels Like"
        unique_id: gazebo_hour_1_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][(now().hour + 1) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 2 Feels Like"
        unique_id: gazebo_hour_2_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][(now().hour + 2) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 3 Feels Like"
        unique_id: gazebo_hour_3_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][(now().hour + 3) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 4 Feels Like"
        unique_id: gazebo_hour_4_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][(now().hour + 4) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 5 Feels Like"
        unique_id: gazebo_hour_5_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][(now().hour + 5) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 6 Feels Like"
        unique_id: gazebo_hour_6_feels_like
        value_template: "{{ value_json['hourly']['apparent_temperature'][(now().hour + 6) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 0 Temperature"
        unique_id: gazebo_hour_0_temperature
        value_template: "{{ value_json['hourly']['temperature'][now().hour] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 1 Temperature"
        unique_id: gazebo_hour_1_temperature
        value_template: "{{ value_json['hourly']['temperature'][(now().hour + 1) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 2 Temperature"
        unique_id: gazebo_hour_2_temperature
        value_template: "{{ value_json['hourly']['temperature'][(now().hour + 2) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 3 Temperature"
        unique_id: gazebo_hour_3_temperature
        value_template: "{{ value_json['hourly']['temperature'][(now().hour + 3) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 4 Temperature"
        unique_id: gazebo_hour_4_temperature
        value_template: "{{ value_json['hourly']['temperature'][(now().hour + 4) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 5 Temperature"
        unique_id: gazebo_hour_5_temperature
        value_template: "{{ value_json['hourly']['temperature'][(now().hour + 5) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 6 Temperature"
        unique_id: gazebo_hour_6_temperature
        value_template: "{{ value_json['hourly']['temperature'][(now().hour + 6) % 24] }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Gazebo Hour 0 Precipitation"
        unique_id: gazebo_hour_0_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][now().hour] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 1 Precipitation"
        unique_id: gazebo_hour_1_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][(now().hour + 1) % 24] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 2 Precipitation"
        unique_id: gazebo_hour_2_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][(now().hour + 2) % 24] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 3 Precipitation"
        unique_id: gazebo_hour_3_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][(now().hour + 3) % 24] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 4 Precipitation"
        unique_id: gazebo_hour_4_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][(now().hour + 4) % 24] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 5 Precipitation"
        unique_id: gazebo_hour_5_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][(now().hour + 5) % 24] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 6 Precipitation"
        unique_id: gazebo_hour_6_precipitation
        value_template: "{{ value_json['hourly']['precipitation_probability'][(now().hour + 6) % 24] }}"
        unit_of_measurement: "%"

      - name: "Gazebo Hour 0 Humidity"
        unique_id: gazebo_hour_0_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][now().hour] }}"
        unit_of_measurement: "%"
        device_class: humidity

      - name: "Gazebo Hour 1 Humidity"
        unique_id: gazebo_hour_1_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][(now().hour + 1) % 24] }}"
        unit_of_measurement: "%"
        device_class: humidity

      - name: "Gazebo Hour 2 Humidity"
        unique_id: gazebo_hour_2_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][(now().hour + 2) % 24] }}"
        unit_of_measurement: "%"
        device_class: humidity

      - name: "Gazebo Hour 3 Humidity"
        unique_id: gazebo_hour_3_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][(now().hour + 3) % 24] }}"
        unit_of_measurement: "%"
        device_class: humidity

      - name: "Gazebo Hour 4 Humidity"
        unique_id: gazebo_hour_4_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][(now().hour + 4) % 24] }}"
        unit_of_measurement: "%"
        device_class: humidity

      - name: "Gazebo Hour 5 Humidity"
        unique_id: gazebo_hour_5_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][(now().hour + 5) % 24] }}"
        unit_of_measurement: "%"
        device_class: humidity

      - name: "Gazebo Hour 6 Humidity"
        unique_id: gazebo_hour_6_humidity
        value_template: "{{ value_json['hourly']['relative_humidity_2m'][(now().hour + 6) % 24] }}"
        unit_of_measurement: "%"
        device_class: humidity

      # Weather codes for weather icons (wxIcon0 to wxIcon6)
      - name: "Gazebo Hour 0 Weather Code"
        unique_id: gazebo_hour_0_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][now().hour] }}"
        unit_of_measurement: ""

      - name: "Gazebo Hour 1 Weather Code"
        unique_id: gazebo_hour_1_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][(now().hour + 1) % 24] }}"
        unit_of_measurement: ""

      - name: "Gazebo Hour 2 Weather Code"
        unique_id: gazebo_hour_2_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][(now().hour + 2) % 24] }}"
        unit_of_measurement: ""

      - name: "Gazebo Hour 3 Weather Code"
        unique_id: gazebo_hour_3_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][(now().hour + 3) % 24] }}"
        unit_of_measurement: ""

      - name: "Gazebo Hour 4 Weather Code"
        unique_id: gazebo_hour_4_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][(now().hour + 4) % 24] }}"
        unit_of_measurement: ""

      - name: "Gazebo Hour 5 Weather Code"
        unique_id: gazebo_hour_5_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][(now().hour + 5) % 24] }}"
        unit_of_measurement: ""

      - name: "Gazebo Hour 6 Weather Code"
        unique_id: gazebo_hour_6_weather_code
        value_template: "{{ value_json['hourly']['weathercode'][(now().hour + 6) % 24] }}"
        unit_of_measurement: ""

group:
  gazebo_sensors:
    name: "Gazebo Weather Sensors"
    entities:
      - sensor.gazebo_current_temperature
      - sensor.gazebo_current_apparent_temperature
      - sensor.gazebo_current_humidity
      - sensor.gazebo_hour_0_weather_code
      - sensor.gazebo_hour_1_weather_code
      - sensor.gazebo_hour_2_weather_code
      - sensor.gazebo_hour_3_weather_code
      - sensor.gazebo_hour_4_weather_code
      - sensor.gazebo_hour_5_weather_code
      - sensor.gazebo_hour_6_weather_code

recorder:
  exclude:
    entities:
      - sensor.gazebo_hour_1_feels_like
      - sensor.gazebo_hour_2_feels_like
      - sensor.gazebo_hour_3_feels_like
      - sensor.gazebo_hour_4_feels_like
      - sensor.gazebo_hour_5_feels_like
      - sensor.gazebo_hour_6_feels_like
      - sensor.gazebo_hour_0_weather_code
      - sensor.gazebo_hour_1_weather_code
      - sensor.gazebo_hour_2_weather_code
      - sensor.gazebo_hour_3_weather_code
      - sensor.gazebo_hour_4_weather_code
      - sensor.gazebo_hour_5_weather_code
      - sensor.gazebo_hour_6_weather_code

shell_command:
  ping_device: ping -c 1 192.168.0.203 > /dev/null 2>&1 && echo success || echo fail

binary_sensor:
  - platform: template
    sensors:
      device_online:
        friendly_name: "Garage Online"
        value_template: "{{ states('shell_command.ping_device') == 'success' }}"
        device_class: connectivity

logger:
  default: warning
  logs:
    homeassistant.components.rest: debug

#lovelace:
#  mode: yaml
#  resources:
#    - url: /local/community/lovelace-card-mod/card-mod.js
#      type: module