# =============================================================================
# GAZEBO THERMOSTAT - BASE CONFIGURATION
# =============================================================================
# This file contains the core ESPHome configuration including:
# - Device settings and boot sequence
# - WiFi and network configuration
# - Time synchronization
# - Basic hardware setup (GPIO, I2C, etc.)
# - Nextion display setup
# =============================================================================

esphome:
  name: gazebo-thermostat
  friendly_name: Gazebo Thermostat
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: -100
    then:
      - logger.log: "ESP32 booting up - initializing Nextion display"
      - delay: 5s
      - lambda: |-
          ESP_LOGI("nextion", "=== ESP32 BOOTING UP ===");
          ESP_LOGI("nextion", "Initializing Nextion display...");
          
          // Just initialize the display, don't set values to 0
          // The sensor updates will handle setting the correct values
          ESP_LOGI("nextion", "Nextion display initialization completed");

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  baud_rate: 0
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.242
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4
  power_save_mode: none
  ap:
    ssid: GazeboThermostat Fallback
    password: !secret ap_password

captive_portal:

http_request:
  useragent: "esphome/device"
  timeout: 10s
  verify_ssl: false
  id: http_request_data

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"
    servers:
      - "time.google.com"
      - "time.nist.gov"
      - "pool.ntp.org"
    on_time_sync:
      then:
        - logger.log: "Time synchronized successfully!"
        - lambda: |-
            auto now = id(sntp_time).now();
            ESP_LOGD("time_sync", "Time sync successful: %04d-%02d-%02d %02d:%02d:%02d", 
                     now.year, now.month, now.day_of_month, 
                     now.hour, now.minute, now.second);

output:
  - platform: gpio
    id: gazebo_relay_out
    pin: GPIO12

switch:
  - platform: output
    id: gazebo_relay
    name: "Gazebo Relay"
    output: gazebo_relay_out
    restore_mode: RESTORE_DEFAULT_OFF

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

web_server:
  port: 80

# =============================================================================
# NEXTION DISPLAY SETUP
# =============================================================================

uart:
  id: uart_nextion
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

display:
  - platform: nextion
    id: nextion0
    uart_id: uart_nextion
    update_interval: 5s
    lambda: |-
      ESP_LOGD("nextion", "Display refresh - data comes from HA sensors");
    on_setup:
      then:
        - logger.log: "Nextion: Initializing display"
        - lambda: |-
            ESP_LOGD("nextion", "Initializing Nextion display...");
            id(nextion0).send_command("page 0");
            delay(1000);
            ESP_LOGD("nextion", "Display initialized on page 0");
