# ESPHome Integration for Gazebo Thermostat
# This file contains the ESPHome device configuration for Home Assistant

esphome:
  gazebo_thermostat:
    name: "gazebo-thermostat"
    platform: ESP32
    board: esp32dev
    on_boot:
      priority: -100
      then:
        - logger.log: "Gazebo Thermostat starting up"
